# Generated by Django 3.1.6 on 2021-04-28 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('completeBy', models.DateField(null=True)),
                ('points', models.IntegerField(default=0)),
                ('reward', models.IntegerField(blank=True, default=0)),
                ('aType', models.CharField(choices=[('Run', 'Run'), ('Swim', 'Swim'), ('Bike', 'Bike'), ('Lift', 'Lift')], default=1, max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
