# Generated by Django 3.1.6 on 2021-04-28 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Swim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('duration', models.DurationField(null=True)),
                ('distance', models.IntegerField(default=0)),
                ('units', models.CharField(choices=[('yd', 'yards'), ('m', 'meters')], default=0, max_length=2)),
                ('course', models.CharField(choices=[('lc', 'Long Course'), ('sc', 'Short Course'), ('ow', 'Open Water')], default=0, max_length=2)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('duration', models.DurationField(null=True)),
                ('distance', models.IntegerField(default=0)),
                ('elevation_gain', models.IntegerField(default=0)),
                ('units', models.CharField(choices=[('km', 'kilometers'), ('mi', 'miles')], default=1, max_length=2)),
                ('route', models.CharField(blank=True, max_length=25, null=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='otherActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('duration', models.DurationField(null=True)),
                ('description', models.CharField(max_length=200)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('movement', models.CharField(choices=[('BS', 'Back Squat'), ('BN', 'Bench Press'), ('DL', 'Deadlift'), ('FS', 'Front Squat'), ('OH', 'Overhead Press'), ('SN', 'Snatch'), ('CJ', 'Clean and Jerk'), ('PU', 'Pullup')], default=0, max_length=2)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
                ('units', models.CharField(choices=[('lb', 'pounds'), ('kg', 'kilograms')], default=0, max_length=2)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('duration', models.DurationField(null=True)),
                ('elevation_gain', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('units', models.CharField(choices=[('km', 'kilometers/meters'), ('mi', 'miles/feet')], default=1, max_length=2)),
                ('route', models.CharField(blank=True, max_length=25, null=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logger.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
