# Generated by Django 3.1.7 on 2021-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aType',
            field=models.CharField(choices=[('Run', 'Run'), ('Swim', 'Swim'), ('Bike', 'Bike'), ('Lift', 'Lift')], default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='item',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
